version: '3'
services:
  api:
      container_name: "uploader-container"
      image: "xls-xlsx-uploader-api"
      ports:
      - "8081:8080"
      depends_on:
      - "database"

  database:
      container_name: "postgres-container"
      image: "postgresql"
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=postgres
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
