#!/bin/bash
# maven x docker script
mvn clean
mvn compile
mvn package 

docker rm -f $(docker ps -aq)
docker rmi -f $(docker images -q xls-xlsx-uploader-api)
docker build -t xls-xlsx-uploader-api:latest .
docker run -d --name uploader-container -p 8081:8080 xls-xlsx-uploader-api
docker container logs uploader-container
